- name: nielsbohr/gpu-notebook
  hosts: all
  vars:
    cuda:
      os_dist: ubuntu2004
      cpu_arch: x86_64
      major_version: 11
      min_version: 3
      version: "11.3"
      pkg_version: "11-3"
      path: "/usr/local/cuda"
    project_name: nielsbohr/gpu-notebook:edge
    notebook:
      user: jovyan
      uid: 1000
    ansible_bender:
      base_image: "nielsbohr/python-notebook:edge"
      target_image:
        name: "{{ project_name }}"
        user: "{{ notebook.user }}"
        working_dir: "/home/{{ notebook.user }}"
        environment:
          CUDA_VERSION: "{{ cuda.version }}"
          NCCL_VERSION: 2.9.6
          CUDNN_VERSION: 8.1.1
          CUDA_PATH: "{{ cuda.path }}"
          # nvidia-container-runtime
          NVIDIA_VISIBLE_DEVICES: all
          NVIDIA_DRIVER_CAPABILITIES: compute,utility
          # set tensorflow verbosity to error level, (default is 0/everything)
          TF_CPP_MIN_LOG_LEVEL: "3"
          # paths
          PATH: "{{ cuda.path }}/bin:$PATH"
          LD_LIBRARY_PATH: "{{ cuda.path }}/lib64:${LD_LIBRARY_PATH}"
      working_container:
        user: root
        volumes:
          # To get caching effects from previous builds
          - /var/lib/containers:/var/lib/containers
  roles:
    - { role: rasmunk-ansible/gpu/cuda }
    - { role: rasmunk-ansible/tools/python, 
        requirements_path: "{{ playbook_dir }}/requirements.txt",
        python_env_name: "python3" }

  tasks:
   - name: hello
     command: echo "Hello World"